### ISSUE TITLE
[BONUS] Tarif des prestations

### ISSUE THREAD

**Issue by documents-design** [documents-org/v2.documents.design#4]
Serait-il possible de récupérer les données des prix des missions ? (non visibles sur le front, mais utiles lorsque je dois faire des tableaux de références pour les appels d'offre). C'est franchement galère de retrouver les factures, surtout quand ce n'est pas moi qui ai facturé :')

**Comment by Lucassifoni** [comment]
Ah, oui ce sera possible

Lucas Sifoni

**Comment by documents-design** [comment]
En fait, ça te servirait de pouvoir cocher *n* projets dans la liste, et d'exporter un Excel avec nom/titre/commanditaire/date/prix/courte description ?

**Comment by documents-design** [comment]
Prix réimportés, mais tout n'a pas pu être automatiquement réinjecté (j'ai du me baser sur ancien titre = nouveau titre).
