### ISSUE TITLE
L'empreinte d'un habitat, construire léger et décarboné

### ISSUE THREAD

**Issue by antoine-documents** [documents-org/v2.documents.design#45]
Je changerai la miniature par la vue d'ensemble avec la voute du Pavillon qui est si stylé !
Titre : l'empreinte d'un habitat, exposition

**Comment by noemiedocuments** [comment]
J'ai du trouver une autre image de type "stylée" que celle cadrée en carré. Pour retrouver le format vignette, on perdait trop d'information.
